"""SPY (S&P 500) + QQQ (Nasdaq-100) constituent universe.

Wikipedia/other constituent sources are blocked by the environment's
network policy (only the Yahoo data provider is reachable), so the
membership list is bundled statically (best-effort as of early 2026).
Download failures for renamed/delisted tickers are handled gracefully by
the data layer, so a slightly stale list is acceptable.
"""
from __future__ import annotations

# S&P 500 (SPY) — broad large-cap list.
SP500 = """
A AAPL ABBV ABNB ABT ACGL ACN ADBE ADI ADM ADP ADSK AEE AEP AES AFL AIG
AIZ AJG AKAM ALB ALGN ALL ALLE AMAT AMCR AMD AME AMGN AMP AMT AMZN ANET
ANSS AON AOS APA APD APH APTV ARE ATO AVB AVGO AVY AWK AXON AXP AZO BA
BAC BALL BAX BBY BDX BEN BG BIIB BK BKNG BKR BLDR BLK BMY BR BRO BSX BX
BXP C CAG CAH CARR CAT CB CBOE CBRE CCI CCL CDNS CDW CE CEG CF CFG CHD
CHRW CHTR CI CINF CL CLX CMCSA CME CMG CMI CMS CNC CNP COF COIN COO COP
COR COST CPAY CPB CPRT CPT CRL CRM CRWD CSCO CSGP CSX CTAS CTRA CTSH CTVA
CVS CVX CZR D DAL DAY DD DECK DE DELL DG DGX DHI DHR DIS DLR DLTR DOC DOV
DOW DPZ DRI DTE DUK DVA DVN DXCM EA EBAY ECL ED EFX EG EIX EL ELV EMN EMR
ENPH EOG EPAM EQIX EQR EQT ERIE ES ESS ETN ETR EVRG EW EXC EXE EXPD EXPE
EXR F FANG FAST FCX FDS FDX FE FFIV FI FICO FIS FITB FOX FOXA FRT FSLR FTNT
FTV GD GDDY GE GEHC GEN GEV GILD GIS GL GLW GM GNRC GOOG GOOGL GPC GPN GRMN
GS GWW HAL HAS HBAN HCA HD HES HIG HII HLT HOLX HON HPE HPQ HRL HSIC HST
HSY HUBB HUM HWM IBM ICE IDXX IEX IFF INCY INTC INTU INVH IP IPG IQV IR
IRM ISRG IT ITW IVZ J JBHT JBL JCI JKHY JNJ JNPR JPM K KDP KEY KEYS KHC
KIM KKR KLAC KMB KMI KMX KO KR KVUE L LDOS LEN LH LHX LII LIN LKQ LLY LMT
LNT LOW LRCX LULU LUV LVS LW LYB LYV MA MAA MAR MAS MCD MCHP MCK MCO MDLZ
MDT MET META MGM MHK MKC MKTX MLM MMC MMM MNST MO MOH MOS MPC MPWR MRK MRNA
MS MSCI MSFT MSI MTB MTCH MTD MU NCLH NDAQ NDSN NEE NEM NFLX NI NKE NOC NOW
NRG NSC NTAP NTRS NUE NVDA NVR NWS NWSA NXPI O ODFL OKE OMC ON ORCL ORLY
OTIS OXY PANW PARA PAYC PAYX PCAR PCG PEG PEP PFE PFG PG PGR PH PHM PKG PLD
PLTR PM PNC PNR PNW PODD POOL PPG PPL PRU PSA PSX PTC PWR PYPL QCOM RCL REG
REGN RF RJF RL RMD ROK ROL ROP ROST RSG RTX RVTY SBAC SBUX SCHW SHW SJM
SLB SMCI SNA SNPS SO SOLV SPG SPGI SRE STE STLD STT STX STZ SWK SWKS SYF
SYK SYY T TAP TDG TDY TECH TEL TER TFC TGT TJX TMO TMUS TPL TPR TRGP TRMB
TROW TRV TSCO TSLA TSN TT TTWO TXN TXT TYL UAL UBER UDR UHS ULTA UNH UNP
UPS URI USB V VICI VLO VLTO VMC VRSK VRSN VRTX VST VTR VTRS VZ WAB WAT WBA
WBD WDC WEC WELL WFC WM WMB WMT WRB WSM WST WTW WY WYNN XEL XOM XYL YUM
ZBH ZBRA ZTS
""".split()

# Nasdaq-100 (QQQ) — most are already in SP500; union dedupes.
NASDAQ100 = """
AAPL ABNB ADBE ADI ADP ADSK AEP AMAT AMD AMGN AMZN ANSS APP ARM ASML AVGO
AXON AZN BIIB BKNG BKR CCEP CDNS CDW CEG CHTR CMCSA COST CPRT CRWD CSCO
CSGP CSX CTAS CTSH DASH DDOG DXCM EA EXC FANG FAST FTNT GEHC GFS GILD
GOOG GOOGL HON IDXX INTC INTU ISRG KDP KHC KLAC LIN LRCX LULU MAR MCHP
MDLZ MELI META MNST MRVL MSFT MU NFLX NVDA NXPI ODFL ON ORLY PANW PAYX
PCAR PDD PEP PLTR PYPL QCOM REGN ROP ROST SBUX SNPS TEAM TMUS TSLA TTD
TTWO TXN VRSK VRTX WBD WDAY XEL ZS
""".split()


def universe() -> list[str]:
    return sorted(set(SP500) | set(NASDAQ100))
